# Preprocessing

Relevant Inputs:
- Relvant Pokemon 1 Stats
    - df 
- Relvant Pokemon 2 Stats
- WeatherAndTime

Ommited Inputs:
- Price

Outputs:
- In Range [-1, 1]

In [1]:
catalog = context.catalog

In [2]:
Submission = catalog.load('Submission')
AvailablePokemons = catalog.load('AvailablePokemons')
Battle_Results = catalog.load('Battle_Results')
Weakness_Pokemon = catalog.load('Weakness_Pokemon')
All_Pokemons = catalog.load('All_Pokemons')

2020-05-18 09:37:23,386 - kedro.io.data_catalog - INFO - Loading data from `Submission` (CSVDataSet)...
2020-05-18 09:37:23,396 - kedro.io.data_catalog - INFO - Loading data from `AvailablePokemons` (CSVDataSet)...
2020-05-18 09:37:23,403 - kedro.io.data_catalog - INFO - Loading data from `Battle_Results` (CSVDataSet)...
2020-05-18 09:37:28,474 - kedro.io.data_catalog - INFO - Loading data from `Weakness_Pokemon` (CSVDataSet)...
2020-05-18 09:37:28,482 - kedro.io.data_catalog - INFO - Loading data from `All_Pokemons` (CSVDataSet)...

In [3]:
Battle_Results.head()

,Name_1,Level_1,Price_1,HP_1,Attack_1,Defense_1,Sp_Atk_1,Sp_Def_1,Speed_1,Legendary_1,...,Price_2,HP_2,Attack_2,Defense_2,Sp_Atk_2,Sp_Def_2,Speed_2,Legendary_2,WeatherAndTime,BattleResult
0,Metapod,30,441,150,36,103,47,47,58,False,...,1589,262,393,306,164,211,253,False,Windy,-262
1,Pinsir,36,1227,196,304,237,129,164,197,False,...,1583,547,127,365,172,172,200,False,Unknown,-424
2,Metapod,15,297,92,26,73,33,33,40,False,...,4913,821,1208,947,504,652,781,False,Windy,-821
3,Pinsir,40,1401,228,346,270,146,187,224,False,...,588,202,47,138,63,63,75,False,Unknown,214
4,Pinsir,12,634,91,157,124,70,86,106,False,...,381,126,32,90,41,41,51,False,Windy,41

In [4]:
Weakness_Pokemon

,Types,Normal,Fire,Water,Electric,Grass,Ice,Fighting,Poison,Ground,Flying,Psychic,Bug,Rock,Ghost,Dragon,Dark,Steel,Fairy
0,Normal,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.6,0.6,1.0,1.0,0.6,1.0
1,Fire,1.0,0.6,0.6,1.0,50.0,6.0,1.0,1.0,1.0,1.0,1.0,6.0,0.6,1.0,0.6,1.0,6.0,1.0
2,Water,1.0,20.0,0.6,1.0,0.6,1.0,1.0,1.0,6.0,1.0,1.0,1.0,6.0,1.0,0.6,1.0,1.0,1.0
3,Electric,1.0,1.0,6.0,0.6,0.6,1.0,1.0,1.0,0.6,6.0,1.0,1.0,1.0,1.0,0.6,1.0,1.0,1.0
4,Grass,1.0,0.6,6.0,1.0,0.6,1.0,1.0,0.6,6.0,0.6,1.0,0.6,6.0,1.0,0.6,1.0,0.6,1.0
5,Ice,1.0,0.6,0.6,1.0,6.0,0.6,1.0,1.0,6.0,6.0,1.0,1.0,1.0,1.0,6.0,1.0,0.6,1.0
6,Fighting,6.0,1.0,1.0,1.0,1.0,6.0,1.0,0.6,1.0,0.6,0.6,0.6,6.0,0.6,1.0,6.0,6.0,0.6
7,Poison,1.0,1.0,1.0,1.0,6.0,1.0,1.0,0.6,0.6,1.0,1.0,1.0,0.6,0.6,1.0,1.0,0.6,6.0
8,Ground,1.0,6.0,1.0,6.0,0.6,1.0,1.0,6.0,1.0,0.6,1.0,0.6,6.0,1.0,1.0,1.0,6.0,1.0
9,Flying,1.0,1.0,1.0,0.6,6.0,1.0,6.0,1.0,1.0,1.0,1.0,6.0,0.6,1.0,1.0,1.0,0.6,1.0
10,Psychic,1.0,1.0,1.0,1.0,1.0,1.0,6.0,6.0,1.0,1.0,0.6,1.0,1.0,1.0,1.0,0.6,0.6,1.0
11,Bug,1.0,0.6,1.0,1.0,6.0,1.0,0.6,0.6,1.0,0.6,6.0,1.0,1.0,0.6,1.0,6.0,0.6,0.6
12,Rock,1.0,6.0,1.0,1.0,1.0,6.0,0.6,1.0,0.6,6.0,1.0,6.0,1.0,1.0,1.0,1.0,0.6,1.0
13,Ghost,0.6,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,6.0,1.0,1.0,6.0,1.0,0.6,1.0,1.0
14,Dragon,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,6.0,1.0,0.6,0.6
15,Dark,1.0,1.0,1.0,1.0,1.0,1.0,0.6,1.0,1.0,1.0,6.0,1.0,1.0,6.0,1.0,0.6,1.0,0.6
16,Steel,1.0,0.6,0.6,0.6,1.0,6.0,1.0,1.0,1.0,1.0,1.0,1.0,6.0,1.0,1.0,1.0,0.6,6.0
17,Fairy,1.0,0.6,1.0,1.0,1.0,1.0,6.0,0.6,1.0,1.0,1.0,1.0,1.0,1.0,6.0,6.0,0.6,1.0

In [6]:
Submission.type()

AttributeError: 'DataFrame' object has no attribute 'type'

In [7]:
Battle_Results.describe()

,Level_1,Price_1,HP_1,Attack_1,Defense_1,Sp_Atk_1,Sp_Def_1,Speed_1,Level_2,Price_2,HP_2,Attack_2,Defense_2,Sp_Atk_2,Sp_Def_2,Speed_2,BattleResult
count,2.719163e+06,2.719163e+06,2.719163e+06,2.719163e+06,2.719163e+06,2.719163e+06,2.719163e+06,2.719163e+06,2.719163e+06,2.719163e+06,2.719163e+06,2.719163e+06,2.719163e+06,2.719163e+06,2.719163e+06,2.719163e+06,2.719163e+06
mean,5.000841e+01,1.780009e+03,3.329481e+02,3.043974e+02,2.872659e+02,2.837187e+02,2.810636e+02,2.906155e+02,4.999958e+01,1.779824e+03,3.329161e+02,3.043613e+02,2.872629e+02,2.836855e+02,2.810360e+02,2.905625e+02,-1.003408e-01
std,2.857987e+01,1.328518e+03,2.620586e+02,2.510274e+02,2.428663e+02,2.435758e+02,2.299945e+02,2.423285e+02,2.857592e+01,1.328581e+03,2.620985e+02,2.509934e+02,2.428696e+02,2.436107e+02,2.300242e+02,2.423243e+02,4.847676e+02
min,1.000000e+00,1.950000e+02,1.000000e+01,5.000000e+00,5.000000e+00,1.500000e+01,2.000000e+01,1.500000e+01,1.000000e+00,1.950000e+02,1.000000e+01,5.000000e+00,5.000000e+00,1.500000e+01,2.000000e+01,1.500000e+01,-2.312000e+03
25%,2.500000e+01,7.290000e+02,1.310000e+02,1.190000e+02,1.110000e+02,1.090000e+02,1.100000e+02,1.130000e+02,2.500000e+01,7.290000e+02,1.300000e+02,1.190000e+02,1.110000e+02,1.090000e+02,1.100000e+02,1.130000e+02,-3.470000e+02
50%,5.000000e+01,1.356000e+03,2.530000e+02,2.220000e+02,2.070000e+02,2.000000e+02,2.030000e+02,2.080000e+02,5.000000e+01,1.356000e+03,2.530000e+02,2.220000e+02,2.070000e+02,2.000000e+02,2.030000e+02,2.080000e+02,-1.000000e+00
75%,7.500000e+01,2.509000e+03,4.720000e+02,4.210000e+02,3.910000e+02,3.820000e+02,3.840000e+02,3.960000e+02,7.500000e+01,2.509000e+03,4.720000e+02,4.210000e+02,3.920000e+02,3.820000e+02,3.840000e+02,3.960000e+02,3.470000e+02
max,9.900000e+01,8.106000e+03,2.312000e+03,1.865000e+03,2.336000e+03,1.685000e+03,1.508000e+03,1.595000e+03,9.900000e+01,8.106000e+03,2.312000e+03,1.865000e+03,2.336000e+03,1.685000e+03,1.508000e+03,1.595000e+03,2.277000e+03

In [8]:
Battle_Results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2719163 entries, 0 to 2719162
Data columns (total 22 columns):
Name_1            object
Level_1           int64
Price_1           int64
HP_1              int64
Attack_1          int64
Defense_1         int64
Sp_Atk_1          int64
Sp_Def_1          int64
Speed_1           int64
Legendary_1       bool
Name_2            object
Level_2           int64
Price_2           int64
HP_2              int64
Attack_2          int64
Defense_2         int64
Sp_Atk_2          int64
Sp_Def_2          int64
Speed_2           int64
Legendary_2       bool
WeatherAndTime    object
BattleResult      int64
dtypes: bool(2), int64(17), object(3)
memory usage: 420.1+ MB